openapi: 3.0.0
info:
  title: InvisiGuard API
  version: 0.2.0
paths:
  /verify:
    post:
      summary: Verify a watermark in a suspect image without the original.
      description: Performs blind geometric correction (using DFT templates) and extracts the watermark.
      tags:
        - Verification
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                  description: The suspect image file (screenshot, resized, etc.)
      responses:
        '200':
          description: Verification result
          content:
            application/json:
              schema:
                type: object
                properties:
                  verified:
                    type: boolean
                    description: Whether a valid watermark was found.
                  watermark_text:
                    type: string
                    nullable: true
                    description: The decoded text if verified.
                  confidence:
                    type: number
                    format: float
                    description: Confidence score (0-1).
                  metadata:
                    type: object
                    properties:
                      rotation_detected:
                        type: number
                        description: Rotation angle corrected (degrees).
                      scale_detected:
                        type: number
                        description: Scale factor corrected.
